name: $(Rev:r)

trigger:
  branches:
    include:
    - '*'

stages:
- stage: Build
  displayName: CI
  variables:
    - group: SX Health Services Terraform Dev
    - group: pet-build
  jobs:
  - template: templates/azure-pipelines-build-template.yml

- stage: QUALITY_ASSURANCE
  displayName: Quality Assurance
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  dependsOn: Build
  variables:
    - group: SX Health Services Terraform Dev
  jobs:
  - template: templates/azure-pipelines-deployment-template.yml
    parameters:
      displayName: Planning for Production Environment
      environment: QA

- stage: PRE_PROD
  displayName: Pre-Production
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  dependsOn: QUALITY_ASSURANCE
  variables:
    - group: SX Health Services Terraform Test
  jobs:
  - template: templates/azure-pipelines-deployment-template.yml
    parameters:
      displayName: Planning for Production Environment
      environment: TEST

- stage: PRODUCTION
  displayName: Production
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  dependsOn: PRE_PROD
  variables:
    - group: SX Health Services Terraform Prod
  jobs:
  - template: templates/azure-pipelines-deployment-template.yml
    parameters:
      displayName: Apply to Production Environment
      environment: PROD

- stage: PUSH
  displayName: Push Release to Artifacts Feed
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  dependsOn: PRODUCTION
  variables:
    - group: C360 Feed Publish
  jobs:
  - template: templates/azure-pipelines-deployment-template.yml
    parameters:
      displayName: AZ CLI Artifact Publish
      environment: PUSH

- stage: BAU
  displayName: BAU & Fracture
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  dependsOn: PRODUCTION
  variables:
    - group: SX Health Services Terraform Dev
  jobs:
  - template: templates/azure-pipelines-deployment-template.yml
    parameters:
      displayName: Apply to Development Environment
      environment: FRACTURE

- stage: SQ4
  displayName: Snoop Dogs
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  dependsOn: PRODUCTION
  variables:
    - group: SX Health Services Terraform Dev
  jobs:
  - template: templates/azure-pipelines-deployment-template.yml
    parameters:
      displayName: Apply to Development Environment
      environment: SNOOP

- stage: SQ5
  displayName: Cat Stevens
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  dependsOn: PRODUCTION
  variables:
    - group: SX Health Services Terraform Dev
  jobs:
  - template: templates/azure-pipelines-deployment-template.yml
    parameters:
      displayName: Apply to Development Environment
      environment: STEVENS
