jobs:
  - deployment: Deploy
    displayName: ${{ parameters.execution }}
    environment: ${{ parameters.environment }}
    pool:
      vmImage: 'windows-2019'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: Download the build artifacts
            inputs:
              buildType: current
              downloadType: single
              artifactName: drop

          # - task: PowerShell@2
          #   displayName: Diag
          #   inputs:
          #     workingDirectory: $(System.ArtifactsDirectory)/drop
          #     targetType: inline
          #     script: dir ; systeminfo

          - task: PowerShell@2
            displayName: CD Process
            env:
              # From Interim AKS - ${{ parameters.environment }}
              SP_APP_ID: $(arm-client-id)
              SP_TENANT_ID: $(arm-tenant-id)
              SP_PASSWORD: $(sp-password)
              SP_PASS_HASH: $(sp-password-md5-hash)

              # C360 Feed Publish
              AZURE_DEVOPS_EXT_PAT: $(AZURE_DEVOPS_EXT_PAT)

            inputs:
              workingDirectory: $(System.ArtifactsDirectory)/drop
              targetType: filePath
              filePath: $(System.ArtifactsDirectory)/drop/release.ps1
              arguments: ${{ parameters.environment }}
