jobs:
  - job: Build
    displayName: Terraform Validation and Conditional Feature Branch
    pool:
      vmImage: 'windows-2019'
    steps:
      - task: SonarSource.sonarqube.15B84CA1-B62F-4A2A-A403-89B77A063157.SonarQubePrepare@4
        displayName: 'Prepare analysis on SonarQube'
        inputs:
          SonarQube: 'SonarQube Service Connection'
          scannerMode: CLI
          configMode: manual
          cliProjectKey: asp.pets.eclaim
          cliProjectName: asp.pets.eclaim
          extraproperties: |
            sonar.exclusions=**/WU_CDAF/**

      - task: PowerShell@2
        displayName: CI Process
        env:
          SP_APP_ID: $(arm-client-id)
          SP_TENANT_ID: $(arm-tenant-id)
          SP_PASSWORD: $(sp-password)
          SP_PASS_HASH: $(sp-password-md5-hash)
          AZURE_DEVOPS_EXT_PAT: $(AZURE_DEVOPS_EXT_PAT)

        inputs:
          targetType: inline
          script: |
            Import-Module Microsoft.PowerShell.Utility
            Import-Module Microsoft.PowerShell.Management
            Import-Module Microsoft.PowerShell.Security
            Invoke-WebRequest -UseBasicParsing http://cdaf.io/static/app/downloads/WU-CDAF-2.4.5.zip -OutFile WU_CDAF.zip
            Expand-Archive .\WU_CDAF.zip
            .\WU_CDAF\automation\entry.ps1 $(Build.BuildNumber) $(Build.SourceBranch) staging@$(Build.ArtifactStagingDirectory)

      - task: SonarSource.sonarqube.6D01813A-9589-4B15-8491-8164AEB38055.SonarQubeAnalyze@4
        displayName: 'Run Code Analysis'
        continueOnError: false

      - task: SonarSource.sonarqube.291ed61f-1ee4-45d3-b1b0-bf822d9095ef.SonarQubePublish@4
        displayName: 'Publish Quality Gate Result'
        continueOnError: false

      - task: PublishBuildArtifacts@1
